# Generated by Django 5.1.4 on 2024-12-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='governorate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.governorate'),
            preserve_default=False,
        ),
    ]
