# Generated by Django 5.1.4 on 2025-01-01 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_nurse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
