# Generated by Django 5.1.4 on 2025-01-01 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_doctor_options_doctor_created_doctor_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalphacility',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='nurse',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='medicalphacility',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalphacility',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
