# Generated by Django 5.1.4 on 2025-02-10 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_doctor_profile_picture_insurancecompany_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
