# Generated by Django 5.1.4 on 2025-02-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_doctor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalphacility',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='medical_phacilities/'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='nurses/'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacies/'),
        ),
    ]
