# Generated by Django 5.1.2 on 2025-02-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_doctor_insurancecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalphacility',
            name='insurancecompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='insurancecompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='insurancecompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.insurancecompany'),
        ),
    ]
