# Generated by Django 5.1.2 on 2025-02-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_medicalphacility_insurancecompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.governorate'),
        ),
        migrations.AlterField(
            model_name='medicalphacility',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.governorate'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.governorate'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.governorate'),
        ),
    ]
