from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),
    path('reset password/', views.forgot_passwordPage, name="forgot-password"),
    path('error/', views.errorPage, name="error"),
    path('add-doctor/', views.add_doctor, name="add_doctor"),
    path('add-pharmacy/', views.add_pharmacy, name="add_pharmacy"),
    path('add-nurse/', views.add_nurse, name="add_nurse"),
    path('add-medical-phacility/', views.add_medical_phacility,
         name="add_medical_phacility"),
    path('add-user/', views.add_user, name='add_user'),
    path('add-insurance-company/',
         views.add_insurance_company, name='add_insurance'),
    path('success/', views.success_page, name='success'),
    path('user-page/', views.userPage, name="userPage"),
    path('view-doctors/', views.viewDoctor, name="view_doctor"),
    path('view-nurses/', views.viewNurse, name="view_nurse"),
    path('view-pharmacies/', views.viewPharmacies, name="view_pharmacy"),
    path('view-medical-phacilities/', views.viewMedicalPhacilities,
         name="view_medical_phacilities"),
    path('view-insurance-companies/', views.viewInsurance,
         name="view_insurance"),
    path('Users/', views.viewUsers,
         name="view_users"),
    path('view-doctors-user/', views.viewDoctoruser, name="view_doctor_user"),
    path('Insurance companies/', views.viewInsuranceuser,
         name="view_insurance_user"),
    path('Pharmacies/', views.viewPharmacyuser, name="view_pharmacy_user"),
    path('Medical-phacilities/', views.viewMedicalPhacilitiesuser,
         name="view_medical_phacility_user"),
    path('Nurses/', views.viewNurseuser,
         name="view_nurse_user"),
    path('doctor/<int:doctor_id>/schedule/',
         views.viewDoctorSchedule, name='doctor_schedule'),
    path('pharmacy/<int:pharmacy_id>/details/',
         views.viewPharmacyDetails, name='pharmacy_details'),
    path('medical-phacility/<int:medical_phacility_id>/details/',
         views.viewMedicalDetails, name='phacility_details'),
    path('nurse/<int:nurse_id>/details/',
         views.viewNurseDetails, name='nurse_details'),
    path('user/<int:userprofile_id>/details/',
         views.viewUserDetails, name='user_details'),
    path('insurance-company/<int:insurance_company_id>/details/',
         views.viewInsuranceCompanyDetails, name='insurance_details'),
    #     path('view-profile-settings/', views.profile_settings, name="profile_settings"),
    path('edit-doctor/<int:doctor_id>/',
         views.edit_doctor, name='editdoctor'),
    path('edit-pharmacy/<int:pharmacy_id>/',
         views.edit_pharmacy, name='editpharmacy'),
    path('edit-medical-phacility/<int:medical_phacility_id>/',
         views.edit_medical_phacility, name='editphacility'),
    path('edit-nurse/<int:nurse_id>/',
         views.edit_nurse, name='editnurse'),
    path('edit-user/<int:user_id>/',
         views.edit_user, name='edituser'),
    path('edit-insurance-company/<int:insurance_company_id>/',
         views.edit_insurance_company, name='edit_insurance_company'),
    path('delete-doctor/<int:doctor_id>/',
         views.delete_doctor, name='delete_doctor'),
    path('delete-pharmacy/<int:pharmacy_id>/',
         views.delete_pharmacy, name='delete_pharmacy'),
    path('delete-phacility/<int:phacility_id>/',
         views.delete_phacility, name='delete_phacility'),
    path('delete-nurse/<int:nurse_id>/',
         views.delete_nurse, name='delete_nurse'),
    path('delete-userprofile/<int:userprofile_id>/',
         views.delete_userprofile, name='delete_user'),
    path('delete-schedule/<int:schedule_id>/',
         views.delete_schedule, name='delete_schedule'),
    path('delete-insurance-company/<int:insurance_company_id>/',
         views.delete_insurance_company, name='delete_insurance_company'),
    path('get-select-options/', views.get_select_options,
         name='get_select_options'),  # Fetch select options
    path('update-doctor/<int:doctor_id>/',
         views.update_doctor, name='update_doctor'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
